apiVersion: apps/v1
kind: Deployment
metadata:
  # reger
  labels:
    app: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/jeff-tekton/ui
          imagePullPolicy: Always
          name: ui
          ports:
            - containerPort: 3000
